### ISSUE TITLE
Hangman: Numbers

### ISSUE THREAD

**Issue by LaraRod** [Hangman-Studios/hangman#38]
I could enter numbers when typing the word. But when guessing the word afterwards, unfortunately, you could not enter numbers.

<img width="499" alt="Hangman_Numbers" src="https://user-images.githubusercontent.com/85410953/120901076-e0fbd200-c638-11eb-85b0-ca411ad202e9.PNG">

**Comment by LaraRod** [comment]
I have a similar problem with entering spaces.

**Comment by PhilippAuch** [comment]
Closed as project is no longer maintained. If this issue is applicable to the redevelopment please resubmit in the future.
