### ISSUE TITLE
Hangman: the hangman is not displayed

### ISSUE THREAD

**Issue by LaraRod** [Hangman-Studios/hangman#39]
Immediately after entering the last wrong letter, the popup "Du bist an der Reihe" appeared.
I would expect to see the entire body for at least a moment. Either you build in a buffer of e.g. 5 seconds or the player has to confirm via a button that he wants to play another round.
<img width="443" alt="Hangman_the hangman is not displayed" src="https://user-images.githubusercontent.com/85410953/120901228-d68e0800-c639-11eb-8c9f-4dc1ce0acb44.PNG">

**Comment by PhilippAuch** [comment]
Closed as project is no longer maintained. If this issue is applicable to the redevelopment please resubmit in the future.
